/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AkarIconsSoundOff: typeof import('~icons/akar-icons/sound-off')['default']
    AkarIconsSoundOn: typeof import('~icons/akar-icons/sound-on')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeroiconsArrowDown20Solid: typeof import('~icons/heroicons/arrow-down20-solid')['default']
    HeroiconsBars3Solid: typeof import('~icons/heroicons/bars3-solid')['default']
    HeroiconsChevronUpDown20Solid: typeof import('~icons/heroicons/chevron-up-down20-solid')['default']
    HeroiconsMicrophoneSolid: typeof import('~icons/heroicons/microphone-solid')['default']
    HeroiconsMoonSolid: typeof import('~icons/heroicons/moon-solid')['default']
    HeroiconsPaperAirplane: typeof import('~icons/heroicons/paper-airplane')['default']
    HeroiconsPaperAirplaneSolid: typeof import('~icons/heroicons/paper-airplane-solid')['default']
    HeroiconsPaperClip20Solid: typeof import('~icons/heroicons/paper-clip20-solid')['default']
    HeroiconsSunSolid: typeof import('~icons/heroicons/sun-solid')['default']
    HeroiconsXMark20Solid: typeof import('~icons/heroicons/x-mark20-solid')['default']
    MessageBox: typeof import('./src/components/MessageBox.vue')['default']
    NotificationStack: typeof import('./src/components/NotificationStack.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectBox: typeof import('./src/components/SelectBox.vue')['default']
    SidePanel: typeof import('./src/components/SidePanel.vue')['default']
    ThemeButton: typeof import('./src/components/ThemeButton.vue')['default']
  }
}
