/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AkarIconsSoundOff: typeof import('~icons/akar-icons/sound-off')['default']
    AkarIconsSoundOn: typeof import('~icons/akar-icons/sound-on')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogPanel: typeof import('@headlessui/vue')['DialogPanel']
    DialogTitle: typeof import('@headlessui/vue')['DialogTitle']
    Header: typeof import('./src/components/Header.vue')['default']
    HeroiconsArrowDown20Solid: typeof import('~icons/heroicons/arrow-down20-solid')['default']
    HeroiconsBars3Solid: typeof import('~icons/heroicons/bars3-solid')['default']
    HeroiconsChevronUpDown20Solid: typeof import('~icons/heroicons/chevron-up-down20-solid')['default']
    HeroiconsDocumentTextSolid: typeof import('~icons/heroicons/document-text-solid')['default']
    HeroiconsGlobeAlt: typeof import('~icons/heroicons/globe-alt')['default']
    HeroiconsMicrophoneSolid: typeof import('~icons/heroicons/microphone-solid')['default']
    HeroiconsMoonSolid: typeof import('~icons/heroicons/moon-solid')['default']
    HeroiconsPaperAirplane: typeof import('~icons/heroicons/paper-airplane')['default']
    HeroiconsPaperAirplaneSolid: typeof import('~icons/heroicons/paper-airplane-solid')['default']
    HeroiconsPaperClip20Solid: typeof import('~icons/heroicons/paper-clip20-solid')['default']
    HeroiconsSunSolid: typeof import('~icons/heroicons/sun-solid')['default']
    HeroiconsXMark20Solid: typeof import('~icons/heroicons/x-mark20-solid')['default']
    Listbox: typeof import('@headlessui/vue')['Listbox']
    ListboxButton: typeof import('@headlessui/vue')['ListboxButton']
    ListboxOption: typeof import('@headlessui/vue')['ListboxOption']
    ListboxOptions: typeof import('@headlessui/vue')['ListboxOptions']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    MessageBox: typeof import('./src/components/MessageBox.vue')['default']
    ModalBox: typeof import('./src/components/ModalBox.vue')['default']
    NotificationStack: typeof import('./src/components/NotificationStack.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectBox: typeof import('./src/components/SelectBox.vue')['default']
    SidePanel: typeof import('./src/components/SidePanel.vue')['default']
    ThemeButton: typeof import('./src/components/ThemeButton.vue')['default']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
  }
}
