
FROM tiangolo/uvicorn-gunicorn:python3.9

RUN pip install --upgrade --no-cache-dir \
    fastapi==0.92.0 \
    websockets==10.4 \
    python-multipart==0.0.6 \
    pandas==1.5.3 \
    scikit-learn==1.2.1 \
    #transformers==4.26.1 add later when using local models \ 
    langchain==0.0.98 \
    qdrant_client==1.0.1 \
    openai==0.27.0